### ISSUE TITLE
Questions related to compiling

### ISSUE THREAD

**Issue by crzran** [vatsimhk/HKCP#19]
Hello,

I'm trying to make a VFPC for VATPRC, and i have already compiled the Sid. However, when running the sln and compiling, I received the following error log:
[VFPC.log](https://github.com/vatsimhk/HKCP/files/12726813/VFPC.log)
Any idea why would this happen? I only changed the name of the plugin from HKvACC VFPC to VATPRC VFPC

**Comment by jamieernest** [comment]
Did you compile it for 32bit? If you compile it for 64bit it will crash

**Comment by crzran** [comment]
You are reeeeeeeeeeeeeeeeeeeeeeeeeeal helpful man, solved
